services:
  postgres:
    image: postgres:15-alpine
    container_name: logscale-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-logscale}
      POSTGRES_USER: ${POSTGRES_USER:-logscale}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./deploy/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U logscale -d logscale"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logscale-api
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-logscale}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-logscale}?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: ./main

volumes:
  postgres_data:
